### PR TITLE
make hardware-lockfile path configurable via config

### PR DESCRIPTION
**Pull request by larsfroelich**
So far, the path to the hardware-lockfile was hard-coded to `/home/pi/Documents/hermes/hermes-hardware.lock`.
This PR makes the file-path for this lockfile configurable as a new entry in the .env environment variables file or through an env variable directly.

### CODE REVIEW

**Comment by patrickjaigner** [comment]
Why do you need to make this path configurable?

**Comment by larsfroelich** [comment]
This makes it possible to run the sensor code on other systems than a
raspberry pi, for example inside a VM (for testing purposes) or on a local
machine (for development purposes), where the folder structure doesn't
match the hard coded path.

**Comment by patrickjaigner** [comment]
Sounds good. I suggest putting these setup parameters into the .env file instead of the config. I'm trying to keep the config for operational purposes.

**Comment by larsfroelich** [comment]
good point, let me look into that

**Review by larsfroelich — COMMENTED** [review]
I've adjusted the PR now, so it now uses an environment variable instead, and included a default value, which also makes this a non-breaking change and no longer touches the configs.

**Comment by larsfroelich** [comment]
superseded by #168 (which is the same PR but based on an internal branch, so the CI-tests can have access to required secrets to pass successfully)

**Pull request closed without merging**
